### ISSUE TITLE
希望tweakmore增加对繁体中文的支援

### ISSUE THREAD

**Issue by Blackrowtw** [Fallen-Breath/tweakermore#12]
你好，最近使用了这个模组一段时间了
一直很疑惑哪里可以找到中文的版本
没想到的是，我把游戏切换成简体中文语系后就出现了 Σ(°Д°; 

希望可以增加对其他中文语系的支援
即便是不需要进行简繁转换
能在繁中游戏内看到简中也很有帮助 (*ﾟーﾟ)b

**Comment by Fallen-Breath** [comment]
我不太希望不经过转换润色地，原封不动地将简体中文翻译复制粘贴为繁体中文翻译，再加上我也不是繁体中文的使用者，我自己也无法构建出优质的繁体中文翻译

不过如果你能接受不经过转换的简体中文的话，你可以使用压缩文件查看器打开 tweakermore 的 jar 文件，将 `assets/tweakermore/lang/zh_tw.json` 拷贝一份，重命名为 `zh_tw.json` 并放入 jar 的同目录 （即其所在路径将为 `assets/tweakermore/lang/zh_tw.json`），即可

如果了解数据包的话，还可将这些语言文件单独制作成一个数据包，方便后续的维护

**Comment by Blackrowtw** [comment]
其实我之前也是用类似的方式
使用醉梦巅峰或是新兵的翻译包很长一段时间了
(是的，我一直有在关注你们Bilibili的生电圈)
不过这种自己增加zh_tw.json的方式实在是太繁琐了

我能理解简繁转换需要润色的问题
不过毕竟合宜的转换需要时间和能力
对于快速更新改版的mod不太方便

不知道能不能使用在GUI切换的形式？
现在最新的masa翻译包也能支援繁体的文本了(谢谢他们)
不太希望tweakmore还要使用自行增加zh_tw.json的方式

**Comment by Fallen-Breath** [comment]
不打算为此专门添加一个切换的功能

关于数据包，模仿着做好了后，就能一直用下去的，只有想要更新语言文件是得手动同步，也不会太麻烦

**Comment by Blackrowtw** [comment]
了解了
那我会尝试往作成数据包的形式进行
感谢你提供的资讯 (*ﾟーﾟ)b
