### ISSUE TITLE
[BUG] 选项显示与masa gadget 冲突，导致显示纯文本

### ISSUE THREAD

**Issue by shenjackyuanjie** [Fallen-Breath/tweakermore#13]
![image](https://user-images.githubusercontent.com/54507071/167305167-b8957b51-d214-490c-8af3-47b6a439b96f.png)

![image](https://user-images.githubusercontent.com/54507071/167305180-a8c530f6-094e-4a45-9576-dbd8db948fcb.png)

同时加载tweakmore和masa gadget时，tweakermore的界面会变为英文，但是

![image](https://user-images.githubusercontent.com/54507071/167305245-bd338dd6-c3a6-448c-bef7-5030ea39b463.png)

如果有资源包翻译的条目则会正常显示

![image](https://user-images.githubusercontent.com/54507071/167305287-f2d7047b-53bb-477b-9bbb-6c0eade7017e.png)

log无异常

**Comment by Fallen-Breath** [comment]
请向 masa gadget 报告该兼容性问题，这是由于 masa gadget，无法在 tweakermore 这边修复

**Comment by shenjackyuanjie** [comment]
报告了，p老师修复之后会close的

**Comment by shenjackyuanjie** [comment]
好，没事了*

**Comment by Fallen-Breath** [comment]
什么叫没事了，此问题被修复了吗？

**Comment by shenjackyuanjie** [comment]
> 什么叫没事了，此问题被修复了吗？

是的，在新版本修复了（跑
