### ISSUE TITLE
[suggestion] add disableCameraLavaSubmersionFog

### ISSUE THREAD

**Issue by Pi3tro88** [Fallen-Breath/tweakermore#15]
pls if possible that work with optifine too, like disableCameraSubmersionFog

**Comment by Fallen-Breath** [comment]
`disableCameraSubmersionFog` should work with water, lava and powder snow, and also work with optifine. If it doesn't work you can describe the issue you met

**Comment by Pi3tro88** [comment]
oh ye, im stupid sorry, i thought it was only for water
