### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by the-just-luke** [Fallen-Breath/tweakermore#2]
![2021-09-28_22 00 34](https://user-images.githubusercontent.com/80728961/135206261-c6c430fb-7d82-46a0-a12f-dc55b84e5bb8.png)

**Comment by Fallen-Breath** [comment]
What is the typo

**Comment by the-just-luke** [comment]
if is spelled "iff" after inventory

**Comment by yuchenxi2000** [comment]
> if is spelled "iff" after inventory

iff == if and only if

**Comment by the-just-luke** [comment]
I did not know that was an acronym
