### ISSUE TITLE
和ToolTip+冲突

### ISSUE THREAD

**Issue by x-yingcan-x** [Fallen-Breath/tweakermore#20]
日志：[https://share.weiyun.com/PjwbQSS6](https://share.weiyun.com/PjwbQSS6)
~~没有其他网盘的屑，还混了点优化模组~~

**Comment by Fallen-Breath** [comment]
看上去 tooltipsplus 直接把潜影盒的相关方法给整个大力覆盖成了空方法，导致了不兼容

https://github.com/itsmiir/tooltipsplus/blob/3e06f9e79b7497287d17810652701670ace2cb5b/src/main/java/com/miir/tooltipsplus/mixin/SuppressShulkerTooltipMixin.java#L39-L40

这样的话不太可能让 tweakermore 的相关特性与 tooltipsplus 共存了，不过我可以在 tooltipsplus 存在时禁用这些冲突的特性

**Comment by x-yingcan-x** [comment]
如果不覆盖的话会咋样，或者有没有可能做成切换型的，再或者干脆禁用tooltipplus潜影盒相关的功能，不是很重要

**Comment by Fallen-Breath** [comment]
> 如果不覆盖的话会咋样，或者有没有可能做成切换型的，再或者干脆禁用tooltipplus潜影盒相关的功能，不是很重要

你得问 tooltipplus 的实现去，其他 mod 是操控不了 tooltipplus 对 mc 的修改是否应用的

**Comment by itsmiir** [comment]
你好，我是tooltips+的开发者。我已经在最新版本中修复了这种不兼容性
https://github.com/itsmiir/tooltipsplus/releases/tag/minor
抱歉尴尬的语言，我正在使用谷歌翻译
