### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by yt6983138** [Fallen-Breath/tweakermore#21]
The log and system info is [here](https://crashy.net/WlsMBCzM93fQUt6x8oGx)
without tweakermore, everything is fine

**Comment by Fallen-Breath** [comment]
It's caused by mc tweak `disableCameraFrustumCulling`, switch off this tweak and the game won't crash anymore. That's the workaround before the incompatibility issue is fixed

**Comment by Fallen-Breath** [comment]
The issue exists in mc 1.18 too

**Comment by yt6983138** [comment]
maybe add a warn that if user try to enable it warn user that make game crash with sodium?

**Comment by yt6983138** [comment]
sorry for late reply, were busy.
also 

> It's caused by mc tweak `disableCameraFrustumCulling`, switch off this tweak and the game won't crash anymore. That's the workaround before the incompatibility issue is fixed

ty, i disabled that in config, everything is fine now
also sorry for late reply, were busy these day
