### ISSUE TITLE
1.18.1-v3.8.1 崩潰問題

### ISSUE THREAD

**Issue by GenMannnnnn** [Fallen-Breath/tweakermore#23]
## Description

單獨安裝tweakermore-mc1.18.2-v3.8.1.jar與malilib-fabric-1.18.1-0.11.8.jar
在遊戲程式開啟時崩潰，無法得到相關錯誤訊息
使用tweakermore-mc1.18.2-v3.7.1.jar則正常可開啟

## To Reproduce

單獨安裝tweakermore-mc1.18.2-v3.8.1.jar與malilib-fabric-1.18.1-0.11.8.jar
fabric-loader 0.14.10
fabric API 0.46.6+1.18

## Log

[crash-2022-11-07_00.09.27-client.txt](https://github.com/Fallen-Breath/tweakermore/files/9946252/crash-2022-11-07_00.09.27-client.txt)
[latest.log](https://github.com/Fallen-Breath/tweakermore/files/9946259/latest.log)

**Comment by Fallen-Breath** [comment]
该崩溃是 Minecraft 1.18.1 和 Minecraft 1.18.2 之间的版本差异引起的。TweakerMore 的 mc1.18.2 版本仅支持 Minecraft 1.18.2，并未做 1.18.1 的支持，无法在 Minecraft 1.18.1 下正常工作算是意料之中的事情
