### ISSUE TITLE
fly drag doesnt work when shift-flying

### ISSUE THREAD

**Issue by Pi3tro88** [Fallen-Breath/tweakermore#24]
## Description
the tweakermore fly drag rule doesnt influence flying if pressing shift+space(optional, to not descend lol) whyle in flying mode

## To Reproduce

1. get in flying mode
2. go forward while pressing shift
3. stop going forward

What you expect to see: the fly drag value should affect the drag speed

What actually happens: 

it doesnt happen

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: 1.18,2
- TweakerMore version: 3.8.1
- Other related mod versions: nah
- ...

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.

**Comment by Fallen-Breath** [comment]
Cannot reproduce

If you were refering to drag in verital flying movement, vanilla itself doesn't provide any drag logic on that

**Comment by Pi3tro88** [comment]
> Cannot reproduce
> 
> If you were refering to drag in verital flying movement, vanilla itself doesn't provide any drag logic on that

nono im referring to the horizontal movement, it doesnt get affected by the flydrag value if are shifting and you stop moving mid air

**Comment by Pi3tro88** [comment]
to me it also happens with only tweakeroo, tweakermore, fabric api and malilib


https://user-images.githubusercontent.com/88508843/204795402-c900d6a2-8014-4d80-9e67-2d357f42a4ba.mp4

**Comment by Pi3tro88** [comment]
its hard to tell the difference cuz when you shift-fly you dont appear to be shifting, but it can you can notice when i slide a bit more

**Comment by Fallen-Breath** [comment]
Still cannot reproduce with:
- tweakermore v3.8.1
- fabric api 0.67.0
- malilib 0.12.0
- (optional) tweakeroo 0.13.3

**Comment by 15801915131** [comment]
Using Tweakeroo.tweakCustomFlatPresets ?

**Comment by Fallen-Breath** [comment]
> Using Tweakeroo.tweakCustomFlatPresets ?

Not that related to this issue. This issue is about the `flyDrag` option

**Comment by 15801915131** [comment]
> > Using Tweakeroo.tweakCustomFlatPresets ?
> 
> Not that related to this issue. This issue is about the `flyDrag` option

I mean whether flyDrag option is compatible with Tweakeroo.tweakCustomFlatPresets?

**Comment by Pi3tro88** [comment]
> > > Using Tweakeroo.tweakCustomFlatPresets ?
> > 
> > 
> > Not that related to this issue. This issue is about the `flyDrag` option
> 
> I mean whether flyDrag option is compatible with Tweakeroo.tweakCustomFlatPresets?

wdym one controls the speed, the other one the deceleration

**Comment by Pi3tro88** [comment]
anyway, im gonna try to reproduce in a "vanilla" istance, maybe its some mods i have

**Comment by Fallen-Breath** [comment]
close as being stale for 1 year
