### ISSUE TITLE
开发环境中无法正常保存配置

### ISSUE THREAD

**Issue by burningtnt** [Fallen-Breath/tweakermore#25]
修改tweakermore配置后无法正常保存配置

复现：
1 在开发环境中将 tweakermore-mc1.18.2-v3.8.1 以 modCompileOnly 导入
2 在 run/mod 中放入 tweakermore-mc1.18.2-v3.8.1，以及 modmenu
3 运行游戏，直到主界面正常显示
4 点击 modmenu 提供的 模组 按钮，找到 tweakermore，点击 设置 按钮，进入 tweakermore 的配置界面
5 任意修改一个功能的 hotkey
6 回到主界面，点击 推出游戏
7 重启游戏，重新按照3 - 4的步骤进入 tweakermore 的配置界面，在步骤5中修改的 hotkey 又回到了先前的设置

依赖信息：
- com_github_llamalad7_mixinextras 0.1.0 via tweakermore
- malilib 0.12.1
- minecraft 1.18.2
- modmenu 3.2.4
- tweakermore 3.8.1

原因猜测：某个关于保存设置的 mixin 的 remap 没有正常加载？

**Comment by Fallen-Breath** [comment]
若与配置文件有关，不妨在问题描述中添加关于 `./config/tweakermore.json` 这一 TweakerMore 配置文件所含内容的描述，如在执行某些操作之后检查这一配置文件中是否正确地储存了相关的内容

请提供出现问题时，游戏的日志。毕竟如果本 issue 与 mixin 相关，日志中总会存在相应的信息

由于本 issue 是开发环境相关的 issue，请提供 loom、fabric-loader 等相关组件的版本信息

**Comment by myl7** [comment]
Same issue with `tweakermore-mc1.19.4-v3.12.0`. And editing the config JSON works fine.
