### ISSUE TITLE
[兼容性问题]与caxton不兼容

### ISSUE THREAD

**Issue by qicansellin** [Fallen-Breath/tweakermore#28]
## Description

与caxton不兼容，游戏无法正常启动

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.3'
- TweakerMore version: 'v1.9.2'
- Other related mod versions: 'caxton-beta v0.3.0'

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.
[错误报告-2023-1-25_9.48.27.zip](https://github.com/Fallen-Breath/tweakermore/files/10495450/-2023-1-25_9.48.27.zip)

**Comment by qicansellin** [comment]
Caxton https://modrinth.com/mod/caxton

**Comment by qicansellin** [comment]
caxton的作者的gitlee中有相关问题 https://gitlab.com/Kyarei/caxton/-/issues/14

**Comment by Fallen-Breath** [comment]
正如 caxton 的 issue 里所述，caxton `@Overwrite` 重写了告示牌渲染方面的代码，这导致其与存在相关修改的 mod 发生冲突

我可以在检测到 caxton 时禁用 `disableSignTextLengthLimit` 这一选项，作为一个不完美但可行的解决方法

**Comment by qicansellin** [comment]
希望可以加入，两个模组都很需要

**Comment by Fallen-Breath** [comment]
> 希望可以加入，两个模组都很需要

“加入”什么

**Comment by qicansellin** [comment]
> > 希望可以加入，两个模组都很需要
> 
> “加入”什么
解决方案

**Comment by bluebear94** [comment]
Hi, I’m the developer of Caxton. The incompatibility has been fixed in [0.3.0-beta.2](https://modrinth.com/mod/caxton/version/hcrJsouu), so it should be sufficient to make the option conflict with version 0.3.0-beta.1 and earlier.

**Comment by Fallen-Breath** [comment]
> Hi, I’m the developer of Caxton. The incompatibility has been fixed in [0.3.0-beta.2](https://modrinth.com/mod/caxton/version/hcrJsouu), so it should be sufficient to make the option conflict with version 0.3.0-beta.1 and earlier.

done
