### ISSUE TITLE
tweakmAutoCollectMaterialListItem ActionBar hint

### ISSUE THREAD

**Issue by Pi3tro88** [Fallen-Breath/tweakermore#30]
## Motivation
I just want to be able to see something on my screen when collecting items instead of getting spammed by messages saying what i just grabbed xd

## Description
tweakmAutoCollectMaterialListItem should use the actionbar instead of the "message" thingy to show the materials you just got, like tweakmAutoFillContainer or tweakmAutoCleanContainer

**Comment by Fallen-Breath** [comment]
I'll suggest to add another option to switch between inform type. The current message thing contains necessary stuffs for some people and I won't just remove it
