### ISSUE TITLE
[BUG] 1.19.4版本与最新版malilib(0.15.4)启动时崩溃

### ISSUE THREAD

**Issue by shinyashen** [Fallen-Breath/tweakermore#33]
## 描述

1.19.4版本的模组与最新版的`malilib`(0.15.4)启动时崩溃

## 复现

加载最新版的`malilib`与`tweakermore`模组后启动游戏

## 环境

- Minecraft版本: `1.19.4`
- TweakerMore版本: `3.11.0`
- malilib版本: `0.15.4`

## Log

[minecraft-exported-logs-2023-05-05T16-46-37.log](https://github.com/Fallen-Breath/tweakermore/files/11404626/minecraft-exported-logs-2023-05-05T16-46-37.log)

**Comment by Fallen-Breath** [comment]
与 #32 重复
