### ISSUE TITLE
关于本mod和masa Gadget支持1.19.4的版本同时安装会导致游戏无法启动

### ISSUE THREAD

**Issue by 100210110** [Fallen-Breath/tweakermore#34]
## Description

A clear and concise description of what the bug is. It's a Minecraft crash, an unexpected behavior, or something not right.

## To Reproduce

1. Go to '同事安装tweakermore和masa Gadget的mod以及完整的前置mod'
2. Click on '启动游戏'
3. Scroll down to '无需多余动作'
4. ...

What you expect to see: '游戏启动，进入到主菜单界面'

What actually happens: '游戏窗口出现一瞬间就崩溃报错'

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '仅仅1.19.4，实测1.19.3安装对应版本不会出问题'
- TweakerMore version: '3.12.0'
- Other related mod versions: 'masa Gadget，3.1.289'
- ...

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.
[错误报告-2023-5-22_1.05.52.zip](https://github.com/Fallen-Breath/tweakermore/files/11533823/-2023-5-22_1.05.52.zip)

**Comment by katyurua** [comment]
我今天在更新mod后也遇到这个问题，顺手测试了一下。
其中 MagicLib 和 Masa Gadget 没有更新。
将问题集中到了以下三个mod：MaLiLib ，Masa Gadget ，TweakerMore。
测试环境 ：
MC 1.19.4 全新安装 ，fabric loader 0.14.21
前置mod：
```
Fabric API | 0.81.1+1.19.4
MagicLib | 0.7.293
```
***
测试 1 ：运行成功
```
MaLiLib | 0.15.3
Masa Gadget | 3.1.289
TweakerMore | 3.11.0
```
***
测试 2：运行失败
```
MaLiLib | 0.15.4
Masa Gadget | 3.1.289
TweakerMore | 3.12.0
```
部分日志：
![2023-05-28_103921](https://github.com/Fallen-Breath/tweakermore/assets/59998095/e930223f-1ac5-4ff7-988e-de5182ab7796)
***

***
### 目前的暂时的解决方案，把 MaLiLib 从 0.15.4 退回到 0.15.3，其他依赖 MaLiLib 的 mod 也退回到支持 0.15.3 的相应版本。等待 Masa Gadget更新，看是否会修复此问题

**Comment by 100210110** [comment]
现已解决，masa Gadget作者在github有测试版，使用该测试版即可，同时要把依赖库也升级到测试版，具体版本可以看启动器提示，
![image](https://github.com/Fallen-Breath/tweakermore/assets/104227884/0e7764c9-c95a-4d20-8e88-466bd70aade1)
