### ISSUE TITLE
与masa gadget冲突

### ISSUE THREAD

**Issue by Silent-Ash1103** [Fallen-Breath/tweakermore#35]
## Description

A clear and concise description of what the bug is. It's a Minecraft crash, an unexpected behavior, or something not right.

## To Reproduce

4. ...

What you expect to see: '...'

What actually happens: '...'

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.4'
- TweakerMore version: '3.12'
- Masa Gadget versions: '3.1289'
- ...
[错误报告-2023-5-28_16.53.17.zip](https://github.com/Fallen-Breath/tweakermore/files/11584117/-2023-5-28_16.53.17.zip)

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.

**Comment by Fallen-Breath** [comment]
与 #34 重复
