### ISSUE TITLE
【bug】旁观模式按1导致崩溃

### ISSUE THREAD

**Issue by 100210110** [Fallen-Breath/tweakermore#36]
## Description

多人模式下旁观者按1会导致游戏崩溃，初步排查是“旁观者传送菜单包含旁观者”功能
tweakermore.spectatorTeleportMenuIncludeSpectator_alwaysEnterIfStatement出现问题

## To Reproduce

1. 进入多人模式
2. 切换到旁观
3. 按下1
4. 游戏闪退

What you expect to see: '弹出旁观者传送菜单'

What actually happens: '游戏崩溃掉了'

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.4'
- TweakerMore version: '3.12.0'
- Other related mod versions: 'tweakeroo0.16.0'
- ...

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.
[日志.txt](https://github.com/Fallen-Breath/tweakermore/files/11692757/default.txt)

**Comment by Fallen-Breath** [comment]
mc1.19.3 里麻将偷偷地把一个变量改成不可变的了，导致了这个 bug

你可以试试 https://github.com/Fallen-Breath/tweakermore/actions/runs/5218096956，应该也许修好了

**Comment by 100210110** [comment]
> mc1.19.3 里麻将偷偷地把一个变量改成不可变的了，导致了这个 bug
> 
> 你可以试试 [https://github.com/Fallen-Breath/tweakermore/actions/runs/5218096956，应该也许修好了](https://github.com/Fallen-Breath/tweakermore/actions/runs/5218096956%EF%BC%8C%E5%BA%94%E8%AF%A5%E4%B9%9F%E8%AE%B8%E4%BF%AE%E5%A5%BD%E4%BA%86)

wow~nice，它修好了，现在不会崩溃啦，谢谢~
