### ISSUE TITLE
[1.19.4, 3.12.0, Incompatibility] Mixin conflict between CheatUtils and TweakerMore (MaxChatHistory)

### ISSUE THREAD

**Issue by tajemniktv** [Fallen-Breath/tweakermore#37]
## Description

There's an incompat that happens with CheatUtils, as per https://github.com/Zergatul/cheatutils/issues/25
If that's possible, my recommendation would be to make modifying chat related features (maximum chat history, chat width etc.) toggleable (would that prevent mixin from loading or smth?), before letting player edit them. 

## To Reproduce

1. Install both [CheatUtils by Zergatul](https://www.curseforge.com/minecraft/mc-mods/cheatutils-by-zergatul) and TweakerMore by Fallen Breath
2. Open the game
3. Crash

What you expect to see: A game starting properly

What actually happens: A crash

## Environment

- Minecraft version: '1.19.4'
- TweakerMore version: '3.12.0'
- Other related mod versions: 'CheatUtils 2.4.0'
- Java:  v20.0.1, amd64 architecture, Eclipse Adoptium.
- Java Arguments: `[-XX:+UseG1GC, -XX:+ParallelRefProcEnabled, -XX:MaxGCPauseMillis=200, -XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -XX:G1NewSizePercent=30, -XX:G1MaxNewSizePercent=40, -XX:G1HeapRegionSize=8M, -XX:G1ReservePercent=20, -XX:G1HeapWastePercent=5, -XX:G1MixedGCCountTarget=4, -XX:InitiatingHeapOccupancyPercent=15, -XX:G1MixedGCLiveThresholdPercent=90, -XX:G1RSetUpdatingPauseTimePercent=5, -XX:SurvivorRatio=32, -XX:+PerfDisableSharedMem, -XX:MaxTenuringThreshold=1, -XX:UseAVX=3, -XX:+UseStringDeduplication, -XX:+UseFastUnorderedTimeStamps, -XX:+UseAES, -XX:+UseAESIntrinsics, -XX:UseSSE=4, -XX:+UseFMA, -XX:AllocatePrefetchStyle=1, -XX:+UseLoopPredicate, -XX:+RangeCheckElimination, -XX:+EliminateLocks, -XX:+DoEscapeAnalysis, -XX:+UseCodeCacheFlushing, -XX:+SegmentedCodeCache, -XX:+UseFastJNIAccessors, -XX:+OptimizeStringConcat, -XX:+UseCompressedOops, -XX:+UseThreadPriorities, -XX:+OmitStackTraceInFastThrow, -XX:+TrustFinalNonStaticFields, -XX:ThreadPriorityPolicy=1, -XX:+UseInlineCaches, -XX:+RewriteBytecodes, -XX:+RewriteFrequentPairs, -XX:+UseNUMA, -XX:-DontCompileHugeMethods, -XX:+UseFPUForSpilling, -XX:+UseFastStosb, -XX:+UseNewLongLShift, -XX:+UseVectorCmov, -XX:+UseXMMForArrayCopy, -XX:+UseXmmI2D, -XX:+UseXmmI2F, -XX:+UseXmmLoadAndClearUpper, -XX:+UseXmmRegToRegMoveAll, -Dfile.encoding=UTF-8, -Xlog:async, -Djava.security.egd=file:/dev/urandom, --add-modules, jdk.incubator.vector, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6144m, -Duser.language=en]`

## Log

Logs, along with the crash report on the bottom: https://mclo.gs/aYX2IOk

`[Render thread/WARN] (Quilt Loader/Mixin) [org.spongepowered.asm.mixin.injection.invoke.RedirectInjector#addTargetNode] @ModifyConstant conflict. Skipping #cheatutils:zergatul.cheatutils.mixins.json:common.MixinChatComponent from mod cheatutils->@ModifyConstant::onModifyMaxChatHistory(I)I with priority 1000, already redirected by #tweakermore:tweakermore.mixins.json:tweaks.mc_tweaks.chatMessageLimit.ChatHudMixin from mod tweakermore->@ModifyConstant::raiseChatLimitTo(I)I with priority 1000`

**Comment by Fallen-Breath** [comment]
ok it's another mod that modifies the chat message limit with `@ModifyConstant` and without setting `require = 0`, so it conflicts with tweakermore's `chatMessageLimit` option 

https://github.com/Zergatul/cheatutils/blob/3b7598df875ed36d2d19871486f9b2aed1dacbb7/common/java/com/zergatul/cheatutils/mixins/common/MixinChatComponent.java#L17-L23

I'll add `cheatutils` to the conflict mod list of tweakermore's `chatMessageLimit` option to resolve this

**Comment by Fallen-Breath** [comment]
Try https://github.com/Fallen-Breath/tweakermore/actions/runs/5230374685 and there should be no conflict with CheatUtils. TweakerMore's `chatMessageLimit` option will be disabled automatically if CheatUtils exists

**Comment by tajemniktv** [comment]
Game loaded fine! although it crashes on joining a world now...
Logs: https://mclo.gs/mm8KLLf
Crash-report: https://mclo.gs/ENQqRoY

**Comment by Fallen-Breath** [comment]
> Game loaded fine! although it crashes on joining a world now... Logs: https://mclo.gs/mm8KLLf Crash-report: https://mclo.gs/ENQqRoY

ah that's some other bug for a dev build, which doesn't related to this issue. fixing now

Try https://github.com/Fallen-Breath/tweakermore/actions/runs/5230890270

**Comment by Fallen-Breath** [comment]
or you can just wait for the next TweakerMore version to be released

**Comment by tajemniktv** [comment]
Build 553 does in fact work fine for now!:) Thank you for your help with the issue!! 
I'm not closing it yet, as the developer might want to keep this issue still open (or not, if so you can simply close it for me lmao)
