### ISSUE TITLE
shulkerItemContentHint not nbt dependent

### ISSUE THREAD

**Issue by Pi3tro88** [Fallen-Breath/tweakermore#38]
### Motivation

i find really annoying that having a tool with a different durability or even the same enchants but in a different order redners the dots like if it was a mixed box, idk why it was like this in the first place, but if you think it could be useful just add a toggle for nbt dependentn

### Description

add a toggle or just remove it

**Comment by Fallen-Breath** [comment]
Comparing NBT is intended. For these nbt-difference-only boxes, I don't think there's a good way to select an item as the mini item for preview. Different nbt / durability might result in different appearances for an item, so you cannot use an item to represent all items in the box, or it might be misleading

**Comment by Pi3tro88** [comment]
idk i think having an item thats enchanted while there are some that arent is defenetly better than showing the dots

**Comment by Fallen-Breath** [comment]
![image](https://github.com/Fallen-Breath/tweakermore/assets/28978806/5547bb1d-3dfc-45b3-855e-b8dbf370f95e)

This should be what you want. A "*" will be appended if the box is filled with nbt-difference-only items
