### ISSUE TITLE
xaero小地图-Freecam兼容问题

### ISSUE THREAD

**Issue by Allenobbin** [Fallen-Breath/tweakermore#39]
### Bug description

当同时安装TweakerMore和BetterPVP时，xaero小地图-Freecam兼容功能显示红色字体，并提示未安装xaero小地图。然而，BetterPVP已内置xaero小地图。

### Steps to reproduce

删除xaero小地图，安装BetterPVP。
安装TweakerMore。
打开TweakerMore的设置界面，找到xaero小地图-Freecam兼容选项。

### Minecraft version

1.20.1

### TweakerMore version

3.14.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
请提供所述 BetterPVP 模组的出处

**Comment by Allenobbin** [comment]
https://chocolateminecraft.com/mods.php

**Comment by Fallen-Breath** [comment]
BetterPVP 并未用 `provides` 声明、 jar-in-jar 等手段告诉 fabric 其内置了 xaero 小地图的功能，因此从 fabric 的层面上看确实不存在 xaero 小地图这一个 mod，因此 tweakermore 的表现是符合预期的
