### ISSUE TITLE
[Not Issue] What Are your Thoughts On adding A toggleable BlackList For The Clean And Fill Boxes, Mostly The Fill Boxes.

### ISSUE THREAD

**Issue by JacktheDevel0per** [Fallen-Breath/tweakermore#4]
This would be for stuff like pickaxes and rockets (When you don't wanna fill them in).

**Comment by Fallen-Breath** [comment]
Whitelist / Blacklist is not neat imo. There's an option named `autoFillContainerThreshold` for you to set. It's default value is `2` which means items spread in only 1 slot will not be selected

**Comment by JacktheDevel0per** [comment]
Ok I'll set it to like 5 lol
