### ISSUE TITLE
autoFillContainer fills villager

### ISSUE THREAD

**Issue by cspoonerprice** [Fallen-Breath/tweakermore#40]
### Bug description

Using autoFillContainer will dump items into a villager, which is odd.

### Steps to reproduce

enable autofillcontainer, have multiple stacks of items in inventory, right click villager

### Expected behavior

villager trading interface to open.  Not to treat them like a container.

### Actual behavior

"Dropped all items in x slots inside Librarian" is shown.

### Minecraft version

1.20

### TweakerMore version

3.14.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
I should just add villager gui into the blacklist of those container processor options, that should fix this issue
