### ISSUE TITLE
Update to 1.20.2

### ISSUE THREAD

**Issue by Notoriousi** [Fallen-Breath/tweakermore#41]
### Motivation

Crashes when activating on 1.20.2: https://mclo.gs/gj2sbur

### Description

Would love to see a update for 1.20.2

**Comment by Fallen-Breath** [comment]
The official malilib doesn't support 1.20.3 yet, so nope for now

**Comment by Fallen-Breath** [comment]
[v3.15.0](https://github.com/Fallen-Breath/tweakermore/tree/v3.15.0) is released with mc1.20.2 support
