### ISSUE TITLE
InventoryPreview with TweakerMore: serverDataSyncer dropping frames on entities

### ISSUE THREAD

**Issue by Ranzuu** [Fallen-Breath/tweakermore#45]
### Bug description

While using **Tweakeroo** _InventoryPreview_ with **TweakerMore** _serverDataSyncer_ (ON) on the server, the selected entity will lag/drop fps. I guess that's caused by de-sync.

[Example video](https://www.youtube.com/watch?v=xGu6ACq9jZ0)

### Steps to reproduce

1.Enable **TweakerMore** _serverDataSyncer_
2.Examine the entity with _InventoryPreview_ from  **Tweakeroo** on **multiplayer** server.

### Expected behavior

Expected not to lag/drop fps the entity.

### Actual behavior

The entity lagged/dropped frames.

### Minecraft version

1.20.2

### TweakerMore version

v3.15.0

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Try https://github.com/Fallen-Breath/tweakermore/actions/runs/7315959759, this should fix the issue
