### ISSUE TITLE
告示牌编辑防误触

### ISSUE THREAD

**Issue by acaciachan** [Fallen-Breath/tweakermore#47]
### Motivation

0

### Description

目前mojang做的告示牌逻辑非常坑：不打蜡的情况下是可以编辑的，但是只要右键一下就会点出编辑界面，而且打开编辑界面一旦输入了或者修改了文字，是无法撤销的，即使按Esc也会保存更改。这使得很多告示牌一旦被打开，就会多出一堆dsawasdwadsadaw等

解决办法：
1.只有在按下某些快捷键的情况下才能右键打开编辑
2.至少按Esc能不保存的退出编辑

**Comment by Fallen-Breath** [comment]
1. 不好实现。打开告示牌编辑界面是服务端下发的，客户端不知道是什么触发了该打开告示牌编辑界面的操作。如果直接把全部情况都搞成需要快捷键，那么会放下告示牌的那一次编辑也会受影响
2. 拆成 2 个需求：esc 不保存、额外的取消编辑丢弃修改的按钮

**Comment by Fallen-Breath** [comment]
esc 不保存、额外的取消编辑丢弃修改的按钮，这两个需求已在 [v3.16.0](https://github.com/Fallen-Breath/tweakermore/releases/tag/v3.16.0) 中实现
