### ISSUE TITLE
1.18的tweakermore最新版会崩溃

### ISSUE THREAD

**Issue by kxsclu** [Fallen-Breath/tweakermore#5]
经过了几次测试，发现1.18的tweakermore会引起崩溃。

**Comment by kxsclu** [comment]
[Uploading 错误报告-2022-2-14_18.44.26.zip…]()


> 经过了几次测试，发现1.18的tweakermore会引起崩溃。

**Comment by kxsclu** [comment]
> 经过了几次测试，发现1.18的tweakermore会引起崩溃。

malilib是不是也要用哪个特定的版本

**Comment by Fallen-Breath** [comment]
请提供错误报告及 mod 列表

**Comment by kxsclu** [comment]
哦换了最新版的malilib发现可以用了。抱歉

**Comment by Fallen-Breath** [comment]
如果能告知 1.18 需要的最低 malilib 版本的话会很有帮助

**Comment by kxsclu** [comment]
最低需要0.11.4版本的malilib 

> 如果能告知 1.18 需要的最低 malilib 版本的话会很有帮助
