### ISSUE TITLE
Adopt Speed Trading features

### ISSUE THREAD

**Issue by sternschnaube** [Fallen-Breath/tweakermore#50]
### Motivation

I'm missing this mod, since it's not updated anymore.

### Description

https://modrinth.com/mod/speed-trading
https://github.com/ModsByLeo/SpeedTrading

I really love the way how the mod was designed - maybe you are interested to adopt it's features 😊

**Comment by Fallen-Breath** [comment]
https://www.curseforge.com/minecraft/mc-mods/easiervillagertrading

**Comment by sternschnaube** [comment]
I loved the way how this mod is doing it, with the additional button, way more.

Currently I can't test it, it's limited to 1.20.1 and 1.20.4, I'm still on 1.20.2.

Thanks for the recommendation, you can close this if you don't plan to integrate it into TweakerMore 😊
