### ISSUE TITLE
注入tweakermore之后左alt相关快捷键导致游戏崩溃

### ISSUE THREAD

**Issue by YIXINGAlien666** [Fallen-Breath/tweakermore#53]
### Bug description

1、第一次：在正常游戏界面按下shift+alt快捷切换输入法，游戏崩溃
2、第二次：手持投影模组工具按下alt移动投影原理图，游戏崩溃

### Steps to reproduce

（1）
1、正常游戏界面按下shift+alt快捷切换输入法
2、游戏卡顿，玩家无法做出任何动作，界面可能会显示白色（无响应），并于数秒钟（5~8秒）后崩溃，
（2）
1、创造模式下加载任意原理图
2、手持投影模组工具（如木棍）切换至模式五
3、移动原理图
4、游戏卡顿，显示无响应，并于数秒后（5~8秒）后崩溃

### Relevant logs

[错误报告-2024-1-25_9.15.45.zip](https://github.com/Fallen-Breath/tweakermore/files/14046075/-2024-1-25_9.15.45.zip)
[错误报告-2024-1-25_10.17.48.zip](https://github.com/Fallen-Breath/tweakermore/files/14046077/-2024-1-25_10.17.48.zip)

### Minecraft version

1.17.1

### TweakerMore version

3.12.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
请升级 tweakeroo 至 mc1.17.1 的最新版本 0.11.0
