### ISSUE TITLE
避免烟花+连点器

### ISSUE THREAD

**Issue by wwwzzzxxx** [Fallen-Breath/tweakermore#55]
### Motivation

破完基岩飞回家，连点器烟花笑哈哈（逃

### Description

仅在客户端给烟花增加cd时间
可以检测一下手上的烟花的飞行时间，如果是3s的话就把最短烟花使用时间变成3s，如果是其它时间的话就设置成对应的时间的
另外，一些人喜欢用三秒的烟花，但是两秒就按一次，所以这个cd希望是可调节1-3秒的烟花的各自的cd时长
也可以再设计一个功能，飞行状态下根据烟花的飞行时间自动右键烟花，用鼠标侧键控制开启这个功能

**Comment by Fallen-Breath** [comment]
这里实际上阐述了 3 个需求：

1. 使用限速的手段，防止连点器释放烟花。这一点也是标题所述的需求
2. 根据烟花持续时间，自动修改 cd 时长。这一点不太好做适配化，因为持续时间 -> cd 的映射关系是主观的，与个人使用习惯关联很大。除此之外，还需要考虑客户端服务端 tps 不同步等情况。不太好做
3. 自动根据某种间隔使用烟花。与标题所述需求无关系，建议新开 issue

**Comment by Fallen-Breath** [comment]
对于上述的点 1，已于 4a76b3654485930969445f63e136cffa4e143fb5 https://github.com/Fallen-Breath/tweakermore/actions/runs/8253739587 中实现
