### ISSUE TITLE
新增功能-keepMessage 保留聊天信息

### ISSUE THREAD

**Issue by Crystal0404** [Fallen-Breath/tweakermore#57]
### Motivation

minecraft从1.20.2开始, 在群组服环境下, 使用```/server```切换服务器后, 聊天栏全部的聊天信息会被清空

[CrystalCarpetAddition](https://github.com/Crystal0404/CrystalCarpetAddition)于1.0.8-alpha引入相关规则实现了聊天信息保留,
但是这个功能不适合做在专注于更改服务端性质的carpet中, 更适合在tweakmore中完成

### Description

使用mixin截获各种聊天信息将其保存在列表中, 通过fabric-api的相关网络事件在合适的时机再次将消息发送在聊天栏中
就可以做到“保留”聊天信息

### Other information

(直接mixin麻将修改的地方貌似会出现一些奇怪的问题, 将消息保存在一个新列表中貌似会更好)

我已经fork了此仓库并完成了相关移植,  如果你同意添加这个功能，我想我可以提交一个PR o/

**Comment by Fallen-Breath** [comment]
这确实是个值得实现的 feature，不过依赖 fabric api 感觉不太是个好方案

**Comment by Crystal0404** [comment]
> 这确实是个值得实现的 feature，不过依赖 fabric api 感觉不太是个好方案

在我的fork中, 缺少fabric-api不会引起崩溃， 只会让这个功能不可用, 不过我还是会去尝试一下脱离fabric-api

**Comment by Fallen-Breath** [comment]
> 直接mixin麻将修改的地方貌似会出现一些奇怪的问题, 将消息保存在一个新列表中貌似会更好

会有什么奇怪的问题？怀疑是实现不正确导致的

这里提到了更好，既然提了那可以说清楚到底是怎么好

**Comment by Fallen-Breath** [comment]
如果你认为你的实现足够完善，那你可以提交一个 PR，这样也方便 review 具体的代码。当然你也可以选择把 PR 设置为 draft

**Comment by Crystal0404** [comment]
> > 直接mixin麻将修改的地方貌似会出现一些奇怪的问题, 将消息保存在一个新列表中貌似会更好
> 
> 会有什么奇怪的问题？怀疑是实现不正确导致的
> 
> 这里提到了更好，既然提了那可以说清楚到底是怎么好

如果额外实现了一个列表, 相比去mixin麻将修改的地方会更容易维护, 这样我们只需要管在哪能够获得聊天框的信息，而不需要去深究mojang到底干了什么, 如果改动了它会引起什么后果. 目前在我的改动中, 联动了提高消息上限这个功能, 也就是说这个列表最多只有1000个元素, 我认为这还是可以接受的

**Comment by Fallen-Breath** [comment]
> 如果额外实现了一个列表, 相比去mixin麻将修改的地方会更容易维护

存疑

> 而不需要去深究mojang到底干了什么, 如果改动了它会引起什么后果

这反而可能会造成潜在的隐患，如与其他 mod 的不兼容等

**Comment by Crystal0404** [comment]
总之我会先尝试脱离fabric-api, 如果不成功, 依赖一个维护良好泛用性极广的前置也是一个不错的选择

**Comment by Fallen-Breath** [comment]
> 依赖一个维护良好泛用性极广的前置也是一个不错的选择

不同意。除非必要，勿增额外依赖。如果确实需要 fabric-api，你可以阐述清楚具体是为何要用且只能用 fabric-api

**Comment by Crystal0404** [comment]
不兼容应该不会发生, 因为我们只是额外建立了一个列表去储存相关信息, 并且只是用mixin拿到聊天框里的信息并储存,并没有修改mc的任何逻辑. 最坏的情况就是两个mod重复实现了这个功能, 导致重复发送.

**Comment by Crystal0404** [comment]
```
    @Inject(
            method = "addMessage(Lnet/minecraft/text/Text;Lnet/minecraft/network/message/MessageSignatureData;ILnet/minecraft/client/gui/hud/MessageIndicator;Z)V",
            at = @At("HEAD")
    )
    private void keepMessage_impl(Text message, MessageSignatureData signature, int ticks, MessageIndicator indicator, boolean refresh, CallbackInfo ci)
    {
        keepMessage.add(message);
    }
```
这是我实现的mixin, 在收到聊天信息时将信息加入我们的列表. 我不是很能想象的出这个mixin可能导致的兼容问题.

不依赖fabric-api应该不是什么问题,  我在修改完成后会来开启一个pr

**Comment by Fallen-Breath** [comment]
> 因为我们只是额外建立了一个列表去储存相关信息, 并且只是用mixin拿到聊天框里的信息并储存

正因如此，如果有其他 mod 需要操作聊天消息内容，会导致 mc 的数据结构中的内容，与该额外列表里的内容，出现不一致

**Comment by Crystal0404** [comment]
> > 因为我们只是额外建立了一个列表去储存相关信息, 并且只是用mixin拿到聊天框里的信息并储存
> 
> 正因如此，如果有其他 mod 需要操作聊天消息内容，会导致 mc 的数据结构中的内容，与该额外列表里的内容，出现不一致

我刚刚找到了一个很好的注入点, 可以完美解决这些问题, 不再需要额外实现列表了XD

**Comment by Crystal0404** [comment]
赞美fallen \o/

**Comment by Fallen-Breath** [comment]
注：1.20.5 的快照 [24w13a](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w13a) 已不再于进入 reconfiguration 阶段时清空聊天信息
