### ISSUE TITLE
希望能有一个自定义视场角的功能

### ISSUE THREAD

**Issue by Magic-riding** [Fallen-Breath/tweakermore#59]
### Motivation

在无法手动改文件的前提下，我在用replaymod录制的时候用30-70的视场角不够用，需要更小或是更大的视场角，这样可以有更多的焦段来录制。

### Description

就类似tweakeroo中的变焦工具 zoom的功能一样，但是可以用开关来激活，而不是要只有一直点击才能激活

**Comment by Fallen-Breath** [comment]
已实现 `fovOverrideEnabled`、`fovOverrideValue` 这两个功能，前者是开关，后者是自定义 fov 的值
