### ISSUE TITLE
Offering porting assistance for 1.20.6 and 1.21

### ISSUE THREAD

**Issue by sakura-ryoko** [Fallen-Breath/tweakermore#60]
### Motivation

Hey I am a fan of your work, and want to offer any `assistance`

### Description

I have stable ports for malilib / tweakeroo / litematica, etc for 1.20.6 and 1.21.0, so let me know if you need something to work with to get your mods up to date for these versions.  Pull the binary's from my repo's:

https://github.com/sakura-ryoko?tab=repositories

Let me know if you need any assistance.

### Other information

I Can fully understand if you're waiting for masa to do the officially branded versions.

**Comment by Fallen-Breath** [comment]
1.21 is not considered yet, cuz it's still not released

for 1.20.6, if you can provide a usable maven dependencies for your ported masa's mod (e.g. with jitpack), I can do the porting thing by myself

**Comment by sakura-ryoko** [comment]
Okay I've never done that yet, so lol I'd have to research jitpack then.

**Comment by Fallen-Breath** [comment]
> Okay I've never done that yet, so lol I'd have to research jitpack then.

You can add a file like [this](https://github.com/TISUnion/Carpet-TIS-Addition/blob/4b1d1672cf8ec532eceff71ce746541c00107c8a/jitpack.yml) to the repos root, and that's enough

**Comment by sakura-ryoko** [comment]
> > Okay I've never done that yet, so lol I'd have to research jitpack then.
> 
> You can add a file like [this](https://github.com/TISUnion/Carpet-TIS-Addition/blob/4b1d1672cf8ec532eceff71ce746541c00107c8a/jitpack.yml) to the repos root, and that's all u need

Which mods did you need jitpacks for?  only malilib ?

**Comment by Fallen-Breath** [comment]
> Which mods did you need jitpacks for? only malilib ? Or all

malilib is required, but if you can setup for all mods listed in [here](https://github.com/Fallen-Breath/tweakermore/blob/cb3f72b55bd7e3f54f48b57c4d7efb1d7b8fe7c4/versions/1.15.2/gradle.properties) it will be much better

**Comment by sakura-ryoko** [comment]
> > Okay I've never done that yet, so lol I'd have to research jitpack then.
> 
> You can add a file like [this](https://github.com/TISUnion/Carpet-TIS-Addition/blob/4b1d1672cf8ec532eceff71ce746541c00107c8a/jitpack.yml) to the repos root, and that's all u need

Added btw to both branches.

**Comment by sakura-ryoko** [comment]
Mainly the networking and the Rendering has changed under malilib, etc idk how many of the interfaces that you're using off hand.

**Comment by sakura-ryoko** [comment]
For 1.21 for example, the VBO rendering was changed quite a bit for 1.21

**Comment by sakura-ryoko** [comment]
Also if there is anything that I changed, or doesn't work for your needs; please ping me under Masa's discord. :)
