### ISSUE TITLE
希望新增自动清空容器功能的来自容器的黑白名单

### ISSUE THREAD

**Issue by MarcoGao123** [Fallen-Breath/tweakermore#61]
### Motivation

在拥有快捷潜影盒的服务器中, 当使用自动清空容器进行喷射合成后, 容易忘记关闭自动清空容器功能就在空中打开末影箱导致全部物品被清空, 目前只有清空物品的黑白名单, 如果设置潜影盒的黑名单会导致无法快速拿取并运输盒装物品, 所以希望添加来自容器的黑白名单去避免这个问题. 谢谢

### Description

可以设置来自容器黑白名单 即可设置仅能清空箱子和潜影盒 或可设置不能清空末影箱

**Comment by Fallen-Breath** [comment]
这并不能算是一个黑白名单，因为所述情况只有“箱子”、“潜影箱”、“末影箱“这种情况，是若干具体对象，而非一个不定长的可自定义名单

由于客户端是无法得知一个 3x9 的非潜影盒容器 GUI 的来源是什么，唯一能知道的信息只有 GUI 的标题，因此所述需求也是无法实现成一个名单列表的。要做，只能做个忽略末影箱的开关（判断 GUI 的标题是否为 "container.enderchest"）

**Comment by MarcoGao123** [comment]
感谢解答
能否增加这个判断gui标题是否为"container.enderchest" 的功能 谢谢

**Comment by Fallen-Breath** [comment]
可以的，下个版本加

**Comment by MarcoGao123** [comment]
个人感觉排除末影箱已能大部分满足我所述需求。 感谢

**Comment by Fallen-Breath** [comment]
[v3.19.0](https://github.com/Fallen-Breath/tweakermore/releases/tag/v3.19.0) 已发布，把 `autoCleanContainerIgnoreEnderChest` 打开，即可在清空容器时，忽略末影箱
