### ISSUE TITLE
MC 1.21 support

### ISSUE THREAD

**Issue by EndesrDragons** [Fallen-Breath/tweakermore#62]
### Motivation

求更新到1.21版本

### Description

求更新到1.21版本

### Other information

求更新到1.21版本

**Comment by Fallen-Breath** [comment]
别急，慢慢等

**Comment by Fallen-Breath** [comment]
[v3.19.0](https://github.com/Fallen-Breath/tweakermore/releases/tag/v3.19.0) 已发布，支持 MC 1.21
