### ISSUE TITLE
提示框内的潜影盒物品填充率提示文本位置不统一

### ISSUE THREAD

**Issue by ComputerCPT** [Fallen-Breath/tweakermore#66]
### Bug description

提示框内的潜影盒物品填充率提示文本位置不统一
（问题出现不限于下列潜影盒、语言、填充度）
![2024-06-30_13 20 18](https://github.com/Fallen-Breath/tweakermore/assets/120709135/1f997800-c6fc-4ec8-910f-c84f220c64bb)
正常（顶格）（？）

![2024-06-30_13 20 15](https://github.com/Fallen-Breath/tweakermore/assets/120709135/9d533083-7f2d-4cef-bcd2-a54478805881)
相对向左偏移1像素

![2024-06-30_13 20 20](https://github.com/Fallen-Breath/tweakermore/assets/120709135/9c79463c-725c-4096-a3e3-43105ea3eb73)
相对向左偏移2像素

不同语言、不同填充度等都会影响提示文本出现的位置

不同填充度演示：
![2024-06-30_14 13 45](https://github.com/Fallen-Breath/tweakermore/assets/120709135/d946a8fb-e4ca-4ce5-b233-fc8ce00abe78)
~<10.00% 同上图三

![2024-06-30_14 13 46](https://github.com/Fallen-Breath/tweakermore/assets/120709135/d23f6aad-b4de-4438-9276-5949f9f08657)
10.00%<~<100.00% 顶格

![2024-06-30_14 13 47](https://github.com/Fallen-Breath/tweakermore/assets/120709135/811041c1-d2d6-4b81-a88b-378a4ccea801)
=100.00% 相对向左偏移2像素

### Steps to reproduce

1.打开潜影盒物品填充率提示
2.将光标悬浮于各类有物品的潜影盒上

### Expected behavior

填充度文本显示，且位置统一

### Actual behavior

填充度文本显示，但位置不统一

### Minecraft version

1.20.4

### TweakerMore version

3.19.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
意料中行为，设计既如此。填充率文本的渲染并非是绝对的右上角，而仅仅是简单地用空格尽可能地逼近右上角
