### ISSUE TITLE
固定窗口尺寸功能和最大化冲突

### ISSUE THREAD

**Issue by acaciachan** [Fallen-Breath/tweakermore#67]
### Bug description

开启固定窗口尺寸功能之后，点击最大化会被强制改成对应尺寸，但是窗口右上角的按钮现实的是已被最大化。

### Steps to reproduce

1

### Expected behavior

最大化依然不受影响，非最大化时起作用

### Minecraft version

1.20.4

### TweakerMore version

latest

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
MC 内部并不理解窗口最大化这一逻辑，不太好区分
