### ISSUE TITLE
flawlessFrames breaks

### ISSUE THREAD

**Issue by RandomlyCoded** [Fallen-Breath/tweakermore#70]
### Bug description

the `flawlessFrames` tweak breaks once you disable and re-enable it
video showcasing the bug: https://youtu.be/x-ThfOgUXTQ

### Steps to reproduce

1. have a machine that causes many piston updates (e.g. a world eater) running
2. enable the `flawlessFrames` tweak
3. disable it
4. close the config GUI
5. enable the `flawlessFrames` tweak again

### Expected behavior

the world eater updates properly on the client side (you can clearly see all dupers and sweepers move)

### Actual behavior

The tweak works when you first enable it, but changes nothing when you enable it again. Enabling it a 3rd time doesn't change anything either

### Minecraft version

1.18.2

### TweakerMore version

3.14.0, 3.20.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by RandomlyCoded** [comment]
the versions mentioned are the only ones I tested, but it is likely most others are affected too since the tweak was never mentioned in any commit

**Comment by RandomlyCoded** [comment]
2.6.14

**Comment by RandomlyCoded** [comment]
updated replaymod to 2.6.18 (latest for MC 1.18.2); didn't change anything

**Comment by RandomlyCoded** [comment]
so... I have been looking at the code for a bit
i'm not really comfortable with java, so I might be wrong, but to me it looks like the following:
- when initially enabling the tweak, `FlawlessFramesHandler.setEnabled` gets called, which installs a hook (I guess the hook is used for updating the chunks?)
- when disabling the tweak, `FlawlessFramesHandler.setEnabled` returns on [line 86](https://github.com/Fallen-Breath/tweakermore/src/main/java/me/fallenbreath/tweakermore/impl/mc_tweaks/flawlessFrames/FlawlessFramesHandler.java#L84) and doesn't uninstall the hook, so it isn't null
- that causes the check `hook == null && enabled` to fail the next time the tweak gets enabled, so `FlawlessFramesHandler.installHook()`doesn't get called

**Comment by Fallen-Breath** [comment]
I totally forget how those spaghetti codes are written, thanks for pointing it out

**Comment by Fallen-Breath** [comment]
Try https://github.com/Fallen-Breath/tweakermore/actions/runs/10116402776

**Comment by RandomlyCoded** [comment]
that build works
