### ISSUE TITLE
CopySignTextToClipBoard cause game crash in 1.16.5

### ISSUE THREAD

**Issue by CanZenith** [Fallen-Breath/tweakermore#71]
### Bug description

The game will crash when copying text from sign, seems like it has conflict with litematica in 1.16.5, caused NoSuchMethodError with method getGenericTrace. The version of litematica is <litematica-fabric-1.16.5-0.0.0-dev.20210917.192300>

### Steps to reproduce

1. press the hot key to copy sign text

### Actual behavior

game crashed

### Relevant logs

[crash-2024-08-04_10.52.39-client.txt](https://github.com/user-attachments/files/16484910/crash-2024-08-04_10.52.39-client.txt)

### Minecraft version

1.16.5

### TweakerMore version

3.20.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
The `includeVerifier` parameter is added between `litematica-fabric-1.16.4-0.0.0-dev.20210612.170003.jar` and `litematica-fabric-1.16.5-0.0.0-dev.20210917.192300.jar`, which causes the issue
