### ISSUE TITLE
(Fabric, 1.30.0/1.30.2, MC1.21, Fabric) Previous VertexConsumerProvider was not null [ShulkerBoxItemContentHintRenderer]

### ISSUE THREAD

**Issue by tajemniktv** [Fallen-Breath/tweakermore#73]
### Bug description

Mined an shulkerbox with saddles, the crash happened. Log seems to explain a lot, hope it's enough to debug the issue. 

### Steps to reproduce

1. Have such an amazing modpack as I do (pls don't)
2. Mine a shulker with saddles and pick it up

### Relevant logs

https://mclo.gs/c6vPb88

### Environment

Minecraft ver: 1.21
TweakerMore ver: Both 3.20 and 3.20.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by tajemniktv** [comment]
Update: it wasn't empty, it had saddles in it

**Comment by tajemniktv** [comment]
Update2: Happens with any shulkerbox that tries to render an item on the hotbar. Mixed work fine. 
Mod incompatibility?

**Comment by tajemniktv** [comment]
Update3: Worked fine before tho iirc. ImmediatelyFast had an update lately. Will try downgrading that as it is also refferenced in logs.

**Comment by tajemniktv** [comment]
Update4: Downgrading to 1.2.18 of ImmediatelyFast fixes the issue. Opening an issue on their end too just in case.

**Comment by Fallen-Breath** [comment]
You can try disabling the mc tweak `shulkerBoxItemContentHint` as a temp workaround for this

**Comment by tajemniktv** [comment]
Indeed disabling said tweak resolves the issue. 
Thankfully seems like it was an easy fix on ImmediatelyFast side, as the 1.2.20 (dev snapshot) version of said mod, works fine with TweakerMore. Cheers!
