### ISSUE TITLE
tweakermore menu is too much on the right

### ISSUE THREAD

**Issue by Pi3tro88** [Fallen-Breath/tweakermore#8]
idk if this is a bug or a feature but its really hard to use the tweakermore menu like this

![image](https://user-images.githubusercontent.com/88508843/154925092-bc07cf88-fcd2-485d-a477-81a652d0ff9e.png)
instead of
![image](https://user-images.githubusercontent.com/88508843/154925183-726d5091-60ac-4732-8d7f-93006e8d7f93.png)

**Comment by Fallen-Breath** [comment]
it's intended to make the panel right aligned tho, but ye i might need to think about people who use small gui scale...

**Comment by Pi3tro88** [comment]
okok

**Comment by Pi3tro88** [comment]
maybe an option to chose  where to align it? idk if is possible to change the position without relaunching the game

**Comment by Fallen-Breath** [comment]
i think i can just add a restriction that the pannel cannot be too far from the left

**Comment by Pi3tro88** [comment]
ok

**Comment by Fallen-Breath** [comment]
try v2.5.0

**Comment by Pi3tro88** [comment]
yeah now its much better
