### ISSUE TITLE
与minihud不兼容

### ISSUE THREAD

**Issue by vocaloidkiss** [Fallen-Breath/tweakermore#83]
### Bug description

3.21.0与minihud0.32.51不兼容

### Steps to reproduce

安装TM3.21.0，minihud0.32.51与所需masa前置

### Expected behavior

不崩溃

### Actual behavior

崩溃，注入错误

### Relevant logs

[crash-2024-11-09_20.35.21-client.txt](https://github.com/user-attachments/files/17718153/crash-2024-11-09_20.35.21-client.txt)

### Minecraft version

1.21

### TweakerMore version

3.21.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与 #79 重复
