### ISSUE TITLE
tweakeroo玩家背包预览与tweakerMore冲突

### ISSUE THREAD

**Issue by chen112235** [Fallen-Breath/tweakermore#85]
### Bug description

游戏崩溃

### Steps to reproduce

开启tweakeroo玩家背包预览，设置快捷键按下快捷键游戏发生崩溃
显示与tweakermore冲突，也不知道是不是提交到这里

### Actual behavior

游戏崩溃

### Relevant logs

[错误报告-2024-11-26_3.04.17.zip](https://github.com/user-attachments/files/17907816/-2024-11-26_3.04.17.zip)

### Minecraft version

1.21

### TweakerMore version

3.22

### Other information

模组版本
tweakeroo版本0.21.53
tweakermore版本3.22.0
malilib版本0.21.2
fabric api 0.102

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
已知问题。tweakermore 暂不兼容 mc1.21+ 的tweakeroo 0.21.53

**Comment by Fallen-Breath** [comment]
另见：#84
