### ISSUE TITLE
tweakermore注入失败游戏无法启动

### ISSUE THREAD

**Issue by goifld** [Fallen-Breath/tweakermore#89]
### Bug description

1.21.1fabric版本0.16.9 fabric api版本0.110.0 
[错误报告-12-29-2024_1.02.07_PM.zip](https://github.com/user-attachments/files/18268600/-12-29-2024_1.02.07_PM.zip)
tweakermore、litematica、tweakeroo三者只能装两个

### Steps to reproduce

仅安装malilib、tweakeroo、tweakermore、litematica三个mod，PCL起动器提示tweakermore注入失败

### Minecraft version

1.21.1

### TweakerMore version

tweakermore-v3.23.0-mc1.21.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与 #88 重复
